/* tslint:disable */
/* eslint-disable */
/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BasicUserCredentialsDto
 */
export interface BasicUserCredentialsDto {
    /**
     * The username of a user.
     * @type {string}
     * @memberof BasicUserCredentialsDto
     */
    username?: string | null;
    /**
     * A password of a user.
     * @type {string}
     * @memberof BasicUserCredentialsDto
     */
    password?: string | null;
}
