/* tslint:disable */
/* eslint-disable */
/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PasswordPolicyRuleDto } from './password-policy-rule-dto';
/**
 * 
 * @export
 * @interface CheckPasswordPolicyRuleDto
 */
export interface CheckPasswordPolicyRuleDto {
    /**
     * A placeholder string that contains the name of a password policy rule.
     * @type {string}
     * @memberof CheckPasswordPolicyRuleDto
     */
    placeholder?: string | null;
    /**
     * A map that describes the characteristics of a password policy rule, such as the minimum number of digits.
     * @type {{ [key: string]: string; }}
     * @memberof CheckPasswordPolicyRuleDto
     */
    parameter?: { [key: string]: string; };
}
