/* tslint:disable */
/* eslint-disable */
/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { VariableValueDto } from './variable-value-dto';
/**
 * 
 * @export
 * @interface CorrelationMessageDto
 */
export interface CorrelationMessageDto {
    /**
     * The name of the message to deliver.
     * @type {string}
     * @memberof CorrelationMessageDto
     */
    messageName?: string | null;
    /**
     * Used for correlation of process instances that wait for incoming messages. Will only correlate to executions that belong to a process instance with the provided business key.
     * @type {string}
     * @memberof CorrelationMessageDto
     */
    businessKey?: string | null;
    /**
     * Used to correlate the message for a tenant with the given id. Will only correlate to executions and process definitions which belong to the tenant. Must not be supplied in conjunction with a `withoutTenantId`.
     * @type {string}
     * @memberof CorrelationMessageDto
     */
    tenantId?: string | null;
    /**
     * A Boolean value that indicates whether the message should only be correlated to executions and process definitions which belong to no tenant or not. Value may only be `true`, as `false` is the default behavior. Must not be supplied in conjunction with a `tenantId`.
     * @type {boolean}
     * @memberof CorrelationMessageDto
     */
    withoutTenantId?: boolean | null;
    /**
     * Used to correlate the message to the process instance with the given id.
     * @type {string}
     * @memberof CorrelationMessageDto
     */
    processInstanceId?: string | null;
    /**
     * Used for correlation of process instances that wait for incoming messages. Has to be a JSON object containing key-value pairs that are matched against process instance variables during correlation. Each key is a variable name and each value a JSON variable value object with the following properties.
     * @type {{ [key: string]: VariableValueDto; }}
     * @memberof CorrelationMessageDto
     */
    correlationKeys?: { [key: string]: VariableValueDto; } | null;
    /**
     * Local variables used for correlation of executions (process instances) that wait for incoming messages. Has to be a JSON object containing key-value pairs that are matched against local variables during correlation. Each key is a variable name and each value a JSON variable value object with the following properties.
     * @type {{ [key: string]: VariableValueDto; }}
     * @memberof CorrelationMessageDto
     */
    localCorrelationKeys?: { [key: string]: VariableValueDto; } | null;
    /**
     * A map of variables that is injected into the triggered execution or process instance after the message has been delivered. Each key is a variable name and each value a JSON variable value object with the following properties.
     * @type {{ [key: string]: VariableValueDto; }}
     * @memberof CorrelationMessageDto
     */
    processVariables?: { [key: string]: VariableValueDto; } | null;
    /**
     * A map of local variables that is injected into the triggered execution or process instance after the message has been delivered. Each key is a variable name and each value a JSON variable value object with the following properties.
     * @type {{ [key: string]: VariableValueDto; }}
     * @memberof CorrelationMessageDto
     */
    processVariablesLocal?: { [key: string]: VariableValueDto; } | null;
    /**
     * A Boolean value that indicates whether the message should be correlated to exactly one entity or multiple entities. If the value is set to `false`, the message will be correlated to exactly one entity (execution or process definition). If the value is set to `true`, the message will be correlated to multiple executions and a process definition that can be instantiated by this message in one go.
     * @type {boolean}
     * @memberof CorrelationMessageDto
     */
    all?: boolean | null;
    /**
     * A Boolean value that indicates whether the result of the correlation should be returned or not. If this property is set to `true`, there will be returned a list of message correlation result objects. Depending on the all property, there will be either one ore more returned results in the list.  The default value is `false`, which means no result will be returned.
     * @type {boolean}
     * @memberof CorrelationMessageDto
     */
    resultEnabled?: boolean | null;
    /**
     * A Boolean value that indicates whether the result of the correlation should contain process variables or not. The parameter resultEnabled should be set to `true` in order to use this it.  The default value is `false`, which means the variables will not be returned.
     * @type {boolean}
     * @memberof CorrelationMessageDto
     */
    variablesInResultEnabled?: boolean | null;
}
