/* tslint:disable */
/* eslint-disable */
/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreateFilterDto
 */
export interface CreateFilterDto {
    /**
     * The resource type of the filter.
     * @type {string}
     * @memberof CreateFilterDto
     */
    resourceType?: string | null;
    /**
     * The name of the filter.
     * @type {string}
     * @memberof CreateFilterDto
     */
    name?: string | null;
    /**
     * The user id of the owner of the filter.
     * @type {string}
     * @memberof CreateFilterDto
     */
    owner?: string | null;
    /**
     * The query of the filter as a JSON object.
     * @type {any}
     * @memberof CreateFilterDto
     */
    query?: any;
    /**
     * The properties of a filter as a JSON object.
     * @type {any}
     * @memberof CreateFilterDto
     */
    properties?: any;
}
