/* tslint:disable */
/* eslint-disable */
/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { VariableValueDto } from './variable-value-dto';
/**
 * 
 * @export
 * @interface ExecutionTriggerDto
 */
export interface ExecutionTriggerDto {
    /**
     * A JSON object containing variable key-value pairs. Each key is a variable name and each value a JSON variable value object.
     * @type {{ [key: string]: VariableValueDto; }}
     * @memberof ExecutionTriggerDto
     */
    variables?: { [key: string]: VariableValueDto; } | null;
}
