/* tslint:disable */
/* eslint-disable */
/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HistoricDetailQueryDtoSorting } from './historic-detail-query-dto-sorting';
/**
 * A historic detail query which defines a group of historic details.
 * @export
 * @interface HistoricDetailQueryDto
 */
export interface HistoricDetailQueryDto {
    /**
     * Filter by process instance id.
     * @type {string}
     * @memberof HistoricDetailQueryDto
     */
    processInstanceId?: string | null;
    /**
     * Only include historic details which belong to one of the passed  process instance ids.
     * @type {Array<string>}
     * @memberof HistoricDetailQueryDto
     */
    processInstanceIdIn?: Array<string> | null;
    /**
     * Filter by execution id.
     * @type {string}
     * @memberof HistoricDetailQueryDto
     */
    executionId?: string | null;
    /**
     * Filter by task id.
     * @type {string}
     * @memberof HistoricDetailQueryDto
     */
    taskId?: string | null;
    /**
     * Filter by activity instance id.
     * @type {string}
     * @memberof HistoricDetailQueryDto
     */
    activityInstanceId?: string | null;
    /**
     * Filter by case instance id.
     * @type {string}
     * @memberof HistoricDetailQueryDto
     */
    caseInstanceId?: string | null;
    /**
     * Filter by case execution id.
     * @type {string}
     * @memberof HistoricDetailQueryDto
     */
    caseExecutionId?: string | null;
    /**
     * Filter by variable instance id.
     * @type {string}
     * @memberof HistoricDetailQueryDto
     */
    variableInstanceId?: string | null;
    /**
     * Only include historic details where the variable updates belong to one of the passed  list of variable types. A list of all supported variable types can be found [here](https://docs.camunda.org/manual/7.18/user-guide/process-engine/variables/#supported-variable-values). **Note:** All non-primitive variables are associated with the type `serializable`.
     * @type {Array<string>}
     * @memberof HistoricDetailQueryDto
     */
    variableTypeIn?: Array<string> | null;
    /**
     * Filter by a  list of tenant ids.
     * @type {Array<string>}
     * @memberof HistoricDetailQueryDto
     */
    tenantIdIn?: Array<string> | null;
    /**
     * Only include historic details that belong to no tenant. Value may only be `true`, as `false` is the default behavior.
     * @type {boolean}
     * @memberof HistoricDetailQueryDto
     */
    withoutTenantId?: boolean | null;
    /**
     * Filter by a user operation id.
     * @type {string}
     * @memberof HistoricDetailQueryDto
     */
    userOperationId?: string | null;
    /**
     * Only include `HistoricFormFields`. Value may only be `true`, as `false` is the default behavior.
     * @type {boolean}
     * @memberof HistoricDetailQueryDto
     */
    formFields?: boolean | null;
    /**
     * Only include `HistoricVariableUpdates`. Value may only be `true`, as `false` is the default behavior.
     * @type {boolean}
     * @memberof HistoricDetailQueryDto
     */
    variableUpdates?: boolean | null;
    /**
     * Excludes all task-related `HistoricDetails`, so only items which have no task id set will be selected. When this parameter is used together with `taskId`, this call is ignored and task details are not excluded. Value may only be `true`, as `false` is the default behavior.
     * @type {boolean}
     * @memberof HistoricDetailQueryDto
     */
    excludeTaskDetails?: boolean | null;
    /**
     * Restrict to historic variable updates that contain only initial variable values. Value may only be `true`, as `false` is the default behavior.
     * @type {boolean}
     * @memberof HistoricDetailQueryDto
     */
    initial?: boolean | null;
    /**
     * Restrict to historic details that occured before the given date (including the date). Default [format](https://docs.camunda.org/manual/7.18/reference/rest/overview/date-format/) `yyyy-MM-dd'T'HH:mm:ss.SSSZ`, e.g., 2013-01-23T14:42:45.000+0200.
     * @type {Date}
     * @memberof HistoricDetailQueryDto
     */
    occurredBefore?: Date | null;
    /**
     * Restrict to historic details that occured after the given date (including the date). Default [format](https://docs.camunda.org/manual/7.18/reference/rest/overview/date-format/) `yyyy-MM-dd'T'HH:mm:ss.SSSZ`, e.g., 2013-01-23T14:42:45.000+0200.
     * @type {Date}
     * @memberof HistoricDetailQueryDto
     */
    occurredAfter?: Date | null;
    /**
     * A JSON array of criteria to sort the result by. Each element of the array is                     a JSON object that specifies one ordering. The position in the array                     identifies the rank of an ordering, i.e., whether it is primary, secondary,                     etc. Does not have an effect for the `count` endpoint.
     * @type {Array<HistoricDetailQueryDtoSorting>}
     * @memberof HistoricDetailQueryDto
     */
    sorting?: Array<HistoricDetailQueryDtoSorting> | null;
}
