/* tslint:disable */
/* eslint-disable */
/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface HistoricExternalTaskLogDto
 */
export interface HistoricExternalTaskLogDto {
    /**
     * The id of the log entry.
     * @type {string}
     * @memberof HistoricExternalTaskLogDto
     */
    id?: string | null;
    /**
     * The id of the external task.
     * @type {string}
     * @memberof HistoricExternalTaskLogDto
     */
    externalTaskId?: string | null;
    /**
     * The time when the log entry has been written.
     * @type {Date}
     * @memberof HistoricExternalTaskLogDto
     */
    timestamp?: Date | null;
    /**
     * The topic name of the associated external task.
     * @type {string}
     * @memberof HistoricExternalTaskLogDto
     */
    topicName?: string | null;
    /**
     * The id of the worker that posessed the most recent lock.
     * @type {string}
     * @memberof HistoricExternalTaskLogDto
     */
    workerId?: string | null;
    /**
     * The number of retries the associated external task has left.
     * @type {number}
     * @memberof HistoricExternalTaskLogDto
     */
    retries?: number | null;
    /**
     * The execution priority the external task had when the log entry was created.
     * @type {number}
     * @memberof HistoricExternalTaskLogDto
     */
    priority?: number | null;
    /**
     * The message of the error that occurred by executing the associated external task.
     * @type {string}
     * @memberof HistoricExternalTaskLogDto
     */
    errorMessage?: string | null;
    /**
     * The id of the activity on which the associated external task was created.
     * @type {string}
     * @memberof HistoricExternalTaskLogDto
     */
    activityId?: string | null;
    /**
     * The id of the activity instance on which the associated external task was created.
     * @type {string}
     * @memberof HistoricExternalTaskLogDto
     */
    activityInstanceId?: string | null;
    /**
     * The execution id on which the associated external task was created.
     * @type {string}
     * @memberof HistoricExternalTaskLogDto
     */
    executionId?: string | null;
    /**
     * The id of the process instance on which the associated external task was created.
     * @type {string}
     * @memberof HistoricExternalTaskLogDto
     */
    processInstanceId?: string | null;
    /**
     * The id of the process definition which the associated external task belongs to.
     * @type {string}
     * @memberof HistoricExternalTaskLogDto
     */
    processDefinitionId?: string | null;
    /**
     * The key of the process definition which the associated external task belongs to.
     * @type {string}
     * @memberof HistoricExternalTaskLogDto
     */
    processDefinitionKey?: string | null;
    /**
     * The id of the tenant that this historic external task log entry belongs to.
     * @type {string}
     * @memberof HistoricExternalTaskLogDto
     */
    tenantId?: string | null;
    /**
     * A flag indicating whether this log represents the creation of the associated external task.
     * @type {boolean}
     * @memberof HistoricExternalTaskLogDto
     */
    creationLog?: boolean | null;
    /**
     * A flag indicating whether this log represents the failed execution of the associated external task.
     * @type {boolean}
     * @memberof HistoricExternalTaskLogDto
     */
    failureLog?: boolean | null;
    /**
     * A flag indicating whether this log represents the successful execution of the associated external task.
     * @type {boolean}
     * @memberof HistoricExternalTaskLogDto
     */
    successLog?: boolean | null;
    /**
     * A flag indicating whether this log represents the deletion of the associated external task.
     * @type {boolean}
     * @memberof HistoricExternalTaskLogDto
     */
    deletionLog?: boolean | null;
    /**
     * The time after which this log should be removed by the History Cleanup job. Default format `yyyy-MM-dd'T'HH:mm:ss.SSSZ`.  For further information, please see the [documentation](https://docs.camunda.org/manual/7.18/reference/rest/overview/date-format/)
     * @type {Date}
     * @memberof HistoricExternalTaskLogDto
     */
    removalTime?: Date | null;
    /**
     * The process instance id of the root process instance that initiated the process containing this log.
     * @type {string}
     * @memberof HistoricExternalTaskLogDto
     */
    rootProcessInstanceId?: string | null;
}
