/* tslint:disable */
/* eslint-disable */
/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HistoricExternalTaskLogQueryDtoSorting } from './historic-external-task-log-query-dto-sorting';
/**
 * A Historic External Task Log instance query which defines a list of Historic External Task Log instances
 * @export
 * @interface HistoricExternalTaskLogQueryDto
 */
export interface HistoricExternalTaskLogQueryDto {
    /**
     * Filter by historic external task log id.
     * @type {string}
     * @memberof HistoricExternalTaskLogQueryDto
     */
    logId?: string | null;
    /**
     * Filter by external task id.
     * @type {string}
     * @memberof HistoricExternalTaskLogQueryDto
     */
    externalTaskId?: string | null;
    /**
     * Filter by an external task topic.
     * @type {string}
     * @memberof HistoricExternalTaskLogQueryDto
     */
    topicName?: string | null;
    /**
     * Filter by the id of the worker that the task was most recently locked by.
     * @type {string}
     * @memberof HistoricExternalTaskLogQueryDto
     */
    workerId?: string | null;
    /**
     * Filter by external task exception message.
     * @type {string}
     * @memberof HistoricExternalTaskLogQueryDto
     */
    errorMessage?: string | null;
    /**
     * Only include historic external task logs which belong to one of the passed activity ids.
     * @type {Array<string>}
     * @memberof HistoricExternalTaskLogQueryDto
     */
    activityIdIn?: Array<string> | null;
    /**
     * Only include historic external task logs which belong to one of the passed activity instance ids.
     * @type {Array<string>}
     * @memberof HistoricExternalTaskLogQueryDto
     */
    activityInstanceIdIn?: Array<string> | null;
    /**
     * Only include historic external task logs which belong to one of the passed execution ids.
     * @type {Array<string>}
     * @memberof HistoricExternalTaskLogQueryDto
     */
    executionIdIn?: Array<string> | null;
    /**
     * Filter by process instance id.
     * @type {string}
     * @memberof HistoricExternalTaskLogQueryDto
     */
    processInstanceId?: string | null;
    /**
     * Filter by process definition id.
     * @type {string}
     * @memberof HistoricExternalTaskLogQueryDto
     */
    processDefinitionId?: string | null;
    /**
     * Filter by process definition key.
     * @type {string}
     * @memberof HistoricExternalTaskLogQueryDto
     */
    processDefinitionKey?: string | null;
    /**
     * Only include historic external task log entries which belong to one of the passed and comma-separated tenant ids.
     * @type {Array<string>}
     * @memberof HistoricExternalTaskLogQueryDto
     */
    tenantIdIn?: Array<string> | null;
    /**
     * Only include historic external task log entries that belong to no tenant. Value may only be `true`, as `false` is the default behavior.
     * @type {boolean}
     * @memberof HistoricExternalTaskLogQueryDto
     */
    withoutTenantId?: boolean | null;
    /**
     * Only include logs for which the associated external task had a priority lower than or equal to the given value. Value must be a valid `long` value.
     * @type {number}
     * @memberof HistoricExternalTaskLogQueryDto
     */
    priorityLowerThanOrEquals?: number | null;
    /**
     * Only include logs for which the associated external task had a priority higher than or equal to the given value. Value must be a valid `long` value.
     * @type {number}
     * @memberof HistoricExternalTaskLogQueryDto
     */
    priorityHigherThanOrEquals?: number | null;
    /**
     * Only include creation logs. Value may only be `true`, as `false` is the default behavior.
     * @type {boolean}
     * @memberof HistoricExternalTaskLogQueryDto
     */
    creationLog?: boolean | null;
    /**
     * Only include failure logs. Value may only be `true`, as `false` is the default behavior.
     * @type {boolean}
     * @memberof HistoricExternalTaskLogQueryDto
     */
    failureLog?: boolean | null;
    /**
     * Only include success logs. Value may only be `true`, as `false` is the default behavior.
     * @type {boolean}
     * @memberof HistoricExternalTaskLogQueryDto
     */
    successLog?: boolean | null;
    /**
     * Only include deletion logs. Value may only be `true`, as `false` is the default behavior.
     * @type {boolean}
     * @memberof HistoricExternalTaskLogQueryDto
     */
    deletionLog?: boolean | null;
    /**
     * An array of criteria to sort the result by. Each element of the array is                        an object that specifies one ordering. The position in the array                        identifies the rank of an ordering, i.e., whether it is primary, secondary,                        etc. Sorting has no effect for `count` endpoints.
     * @type {Array<HistoricExternalTaskLogQueryDtoSorting>}
     * @memberof HistoricExternalTaskLogQueryDto
     */
    sorting?: Array<HistoricExternalTaskLogQueryDtoSorting> | null;
}
