/* tslint:disable */
/* eslint-disable */
/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface HistoricDecisionInstanceStatisticsDto
 */
export interface HistoricDecisionInstanceStatisticsDto {
    /**
     * A key of decision definition.
     * @type {string}
     * @memberof HistoricDecisionInstanceStatisticsDto
     */
    decisionDefinitionKey?: string | null;
    /**
     * A number of evaluation for decision definition.
     * @type {number}
     * @memberof HistoricDecisionInstanceStatisticsDto
     */
    evaluations?: number | null;
}
