/* tslint:disable */
/* eslint-disable */
/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface HistoricDetailQueryDtoSorting
 */
export interface HistoricDetailQueryDtoSorting {
    /**
     * Sort the results lexicographically by a given criterion. Must be used in conjunction with the sortOrder parameter.
     * @type {string}
     * @memberof HistoricDetailQueryDtoSorting
     */
    sortBy?: HistoricDetailQueryDtoSortingSortByEnum;
    /**
     * Sort the results in a given order. Values may be `asc` for ascending order or `desc` for descending order. Must be used in conjunction with the sortBy parameter.
     * @type {string}
     * @memberof HistoricDetailQueryDtoSorting
     */
    sortOrder?: HistoricDetailQueryDtoSortingSortOrderEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum HistoricDetailQueryDtoSortingSortByEnum {
    ProcessInstanceId = 'processInstanceId',
    VariableName = 'variableName',
    VariableType = 'variableType',
    VariableRevision = 'variableRevision',
    FormPropertyId = 'formPropertyId',
    Time = 'time',
    Occurrence = 'occurrence',
    TenantId = 'tenantId'
}
/**
    * @export
    * @enum {string}
    */
export enum HistoricDetailQueryDtoSortingSortOrderEnum {
    Asc = 'asc',
    Desc = 'desc'
}

