/* tslint:disable */
/* eslint-disable */
/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface HistoricDecisionInputInstanceDto
 */
export interface HistoricDecisionInputInstanceDto {
    /**
     * The id of the decision input value.
     * @type {string}
     * @memberof HistoricDecisionInputInstanceDto
     */
    id?: string | null;
    /**
     * The id of the decision instance the input value belongs to.
     * @type {string}
     * @memberof HistoricDecisionInputInstanceDto
     */
    decisionInstanceId?: string | null;
    /**
     * The id of the clause the input value belongs to.
     * @type {string}
     * @memberof HistoricDecisionInputInstanceDto
     */
    clauseId?: string | null;
    /**
     * The name of the clause the input value belongs to.
     * @type {string}
     * @memberof HistoricDecisionInputInstanceDto
     */
    clauseName?: string | null;
    /**
     * An error message in case a Java Serialized Object could not be de-serialized.
     * @type {string}
     * @memberof HistoricDecisionInputInstanceDto
     */
    errorMessage?: string | null;
    /**
     * The value type of the variable.
     * @type {string}
     * @memberof HistoricDecisionInputInstanceDto
     */
    type?: string | null;
    /**
     * The time the variable was inserted.  [Default format](https://docs.camunda.org/manual/7.18/reference/rest/overview/date-format/) `yyyy-MM-dd'T'HH:mm:ss.SSSZ`.
     * @type {Date}
     * @memberof HistoricDecisionInputInstanceDto
     */
    createTime?: Date | null;
    /**
     * The time after which the entry should be removed by the History Cleanup job. [Default format](https://docs.camunda.org/manual/7.18/reference/rest/overview/date-format/) `yyyy-MM-dd'T'HH:mm:ss.SSSZ`.
     * @type {Date}
     * @memberof HistoricDecisionInputInstanceDto
     */
    removalTime?: Date | null;
    /**
     * The process instance id of the root process instance that initiated the process containing this entry.
     * @type {string}
     * @memberof HistoricDecisionInputInstanceDto
     */
    rootProcessInstanceId?: string | null;
    /**
     * The variable's value. Value differs depending on the variable's type and on the `disableCustomObjectDeserialization` parameter.
     * @type {any}
     * @memberof HistoricDecisionInputInstanceDto
     */
    value?: any;
    /**
     * A JSON object containing additional, value-type-dependent properties.  For variables of type `Object`, the following properties are returned:  * `objectTypeName`: A string representation of the object's type name.  * `serializationDataFormat`: The serialization format used to store the variable.
     * @type {{ [key: string]: any; }}
     * @memberof HistoricDecisionInputInstanceDto
     */
    valueInfo?: { [key: string]: any; };
}
