/* tslint:disable */
/* eslint-disable */
/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface JobDto
 */
export interface JobDto {
    /**
     * The id of the job.
     * @type {string}
     * @memberof JobDto
     */
    id?: string | null;
    /**
     * The id of the associated job definition.
     * @type {string}
     * @memberof JobDto
     */
    jobDefinitionId?: string | null;
    /**
     * The date on which this job is supposed to be processed.
     * @type {Date}
     * @memberof JobDto
     */
    dueDate?: Date | null;
    /**
     * The id of the process instance which execution created the job.
     * @type {string}
     * @memberof JobDto
     */
    processInstanceId?: string | null;
    /**
     * The specific execution id on which the job was created.
     * @type {string}
     * @memberof JobDto
     */
    executionId?: string | null;
    /**
     * The id of the process definition which this job belongs to.
     * @type {string}
     * @memberof JobDto
     */
    processDefinitionId?: string | null;
    /**
     * The key of the process definition which this job belongs to.
     * @type {string}
     * @memberof JobDto
     */
    processDefinitionKey?: string | null;
    /**
     * The number of retries this job has left.
     * @type {number}
     * @memberof JobDto
     */
    retries?: number | null;
    /**
     * The message of the exception that occurred, the last time the job was executed. Is null when no exception occurred.
     * @type {string}
     * @memberof JobDto
     */
    exceptionMessage?: string | null;
    /**
     * The id of the activity on which the last exception occurred, the last time the job was executed. Is null when no exception occurred.
     * @type {string}
     * @memberof JobDto
     */
    failedActivityId?: string | null;
    /**
     * A flag indicating whether the job is suspended or not.
     * @type {boolean}
     * @memberof JobDto
     */
    suspended?: boolean | null;
    /**
     * The job's priority for execution.
     * @type {number}
     * @memberof JobDto
     */
    priority?: number | null;
    /**
     * The id of the tenant which this job belongs to.
     * @type {string}
     * @memberof JobDto
     */
    tenantId?: string | null;
    /**
     * The date on which this job has been created.
     * @type {Date}
     * @memberof JobDto
     */
    createTime?: Date | null;
}
