/* tslint:disable */
/* eslint-disable */
/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { VariableValueDto } from './variable-value-dto';
/**
 * 
 * @export
 * @interface MigrationPlanGenerationDto
 */
export interface MigrationPlanGenerationDto {
    /**
     * The id of the source process definition for the migration.
     * @type {string}
     * @memberof MigrationPlanGenerationDto
     */
    sourceProcessDefinitionId?: string | null;
    /**
     * The id of the target process definition for the migration.
     * @type {string}
     * @memberof MigrationPlanGenerationDto
     */
    targetProcessDefinitionId?: string | null;
    /**
     * A boolean flag indicating whether instructions between events should be configured to update the event triggers.
     * @type {boolean}
     * @memberof MigrationPlanGenerationDto
     */
    updateEventTriggers?: boolean | null;
    /**
     * A map of variables which will be set into the process instances' scope. Each key is a variable name and each value a JSON variable value object.
     * @type {{ [key: string]: VariableValueDto; }}
     * @memberof MigrationPlanGenerationDto
     */
    variables?: { [key: string]: VariableValueDto; } | null;
}
