/* tslint:disable */
/* eslint-disable */
/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MigrationInstructionDto } from './migration-instruction-dto';
import { VariableValueDto } from './variable-value-dto';
/**
 * 
 * @export
 * @interface MigrationPlanDto
 */
export interface MigrationPlanDto {
    /**
     * The id of the source process definition for the migration.
     * @type {string}
     * @memberof MigrationPlanDto
     */
    sourceProcessDefinitionId?: string | null;
    /**
     * The id of the target process definition for the migration.
     * @type {string}
     * @memberof MigrationPlanDto
     */
    targetProcessDefinitionId?: string | null;
    /**
     * A list of migration instructions which map equal activities. Each migration instruction is a JSON object with the following properties:
     * @type {Array<MigrationInstructionDto>}
     * @memberof MigrationPlanDto
     */
    instructions?: Array<MigrationInstructionDto> | null;
    /**
     * A map of variables which will be set into the process instances' scope. Each key is a variable name and each value a JSON variable value object.
     * @type {{ [key: string]: VariableValueDto; }}
     * @memberof MigrationPlanDto
     */
    variables?: { [key: string]: VariableValueDto; } | null;
}
