/* tslint:disable */
/* eslint-disable */
/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MultiFormAttachmentDto
 */
export interface MultiFormAttachmentDto {
    /**
     * The name of the attachment.
     * @type {string}
     * @memberof MultiFormAttachmentDto
     */
    attachmentName?: string | null;
    /**
     * The description of the attachment.
     * @type {string}
     * @memberof MultiFormAttachmentDto
     */
    attachmentDescription?: string | null;
    /**
     * The type of the attachment.
     * @type {string}
     * @memberof MultiFormAttachmentDto
     */
    attachmentType?: string | null;
    /**
     * The url to the remote content of the attachment.
     * @type {string}
     * @memberof MultiFormAttachmentDto
     */
    url?: string | null;
    /**
     * The content of the attachment.
     * @type {Blob}
     * @memberof MultiFormAttachmentDto
     */
    content?: Blob | null;
}
