/* tslint:disable */
/* eslint-disable */
/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProcessInstanceModificationInstructionDto } from './process-instance-modification-instruction-dto';
/**
 * 
 * @export
 * @interface ProcessInstanceModificationDto
 */
export interface ProcessInstanceModificationDto {
    /**
     * Skip execution listener invocation for activities that are started or ended as part of this request.
     * @type {boolean}
     * @memberof ProcessInstanceModificationDto
     */
    skipCustomListeners?: boolean | null;
    /**
     * Skip execution of [input/output variable mappings](https://docs.camunda.org/manual/7.18/user-guide/process-engine/variables/#input-output-variable-mapping) for activities that are started or ended as part of this request.
     * @type {boolean}
     * @memberof ProcessInstanceModificationDto
     */
    skipIoMappings?: boolean | null;
    /**
     * JSON array of modification instructions. The instructions are executed in the order they are in.
     * @type {Array<ProcessInstanceModificationInstructionDto>}
     * @memberof ProcessInstanceModificationDto
     */
    instructions?: Array<ProcessInstanceModificationInstructionDto> | null;
    /**
     * An arbitrary text annotation set by a user for auditing reasons.
     * @type {string}
     * @memberof ProcessInstanceModificationDto
     */
    annotation?: string | null;
}
