/* tslint:disable */
/* eslint-disable */
/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ProcessDefinitionSuspensionStateDto
 */
export interface ProcessDefinitionSuspensionStateDto {
    /**
     * A `Boolean` value which indicates whether to activate or suspend all process definitions with the given key. When the value is set to `true`, all process definitions with the given key will be suspended and when the value is set to `false`, all process definitions with the given key will be activated.
     * @type {boolean}
     * @memberof ProcessDefinitionSuspensionStateDto
     */
    suspended?: boolean | null;
    /**
     * The id of the process definitions to activate or suspend.
     * @type {string}
     * @memberof ProcessDefinitionSuspensionStateDto
     */
    processDefinitionId?: string | null;
    /**
     * The key of the process definitions to activate or suspend.
     * @type {string}
     * @memberof ProcessDefinitionSuspensionStateDto
     */
    processDefinitionKey?: string | null;
    /**
     * A `Boolean` value which indicates whether to activate or suspend also all process instances of  the process definitions with the given key. When the value is set to `true`, all process instances of the process definitions with the given key will be activated or suspended and when the value is set to `false`, the suspension state of  all process instances of the process definitions with the given key will not be updated.
     * @type {boolean}
     * @memberof ProcessDefinitionSuspensionStateDto
     */
    includeProcessInstances?: boolean | null;
    /**
     * The date on which all process definitions with the given key will be activated or suspended. If `null`, the suspension state of all process definitions with the given key is updated immediately. By [default](https://docs.camunda.org/manual/7.18/reference/rest/overview/date-format/), the date must have the format `yyyy-MM-dd'T'HH:mm:ss.SSSZ`, e.g., `2013-01-23T14:42:45.000+0200`.
     * @type {Date}
     * @memberof ProcessDefinitionSuspensionStateDto
     */
    executionDate?: Date | null;
}
