/* tslint:disable */
/* eslint-disable */
/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * A JSON object with the following properties:
 * @export
 * @interface RedeploymentDto
 */
export interface RedeploymentDto {
    /**
     * A list of deployment resource ids to re-deploy.
     * @type {Array<string>}
     * @memberof RedeploymentDto
     */
    resourceIds?: Array<string> | null;
    /**
     * A list of deployment resource names to re-deploy.
     * @type {Array<string>}
     * @memberof RedeploymentDto
     */
    resourceNames?: Array<string> | null;
    /**
     * Sets the source of the deployment.
     * @type {string}
     * @memberof RedeploymentDto
     */
    source?: string | null;
}
