/* tslint:disable */
/* eslint-disable */
/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HistoricProcessInstanceQueryDto } from './historic-process-instance-query-dto';
import { RestartProcessInstanceModificationInstructionDto } from './restart-process-instance-modification-instruction-dto';
/**
 * 
 * @export
 * @interface RestartProcessInstanceDto
 */
export interface RestartProcessInstanceDto {
    /**
     * A list of process instance ids to restart.
     * @type {Array<string>}
     * @memberof RestartProcessInstanceDto
     */
    processInstanceIds?: Array<string> | null;
    /**
     * 
     * @type {HistoricProcessInstanceQueryDto}
     * @memberof RestartProcessInstanceDto
     */
    historicProcessInstanceQuery?: HistoricProcessInstanceQueryDto;
    /**
     * Skip execution listener invocation for activities that are started as part of this request.
     * @type {boolean}
     * @memberof RestartProcessInstanceDto
     */
    skipCustomListeners?: boolean | null;
    /**
     * Skip execution of [input/output variable mappings](https://docs.camunda.org/manual/7.18/user-guide/process-engine/variables/#input-output-variable-mapping) for activities that are started as part of this request.
     * @type {boolean}
     * @memberof RestartProcessInstanceDto
     */
    skipIoMappings?: boolean | null;
    /**
     * Set the initial set of variables during restart. By default, the last set of variables is used.
     * @type {boolean}
     * @memberof RestartProcessInstanceDto
     */
    initialVariables?: boolean | null;
    /**
     * Do not take over the business key of the historic process instance.
     * @type {boolean}
     * @memberof RestartProcessInstanceDto
     */
    withoutBusinessKey?: boolean | null;
    /**
     * **Optional**. A JSON array of instructions that specify which activities to start the process instance at. If this property is omitted, the process instance starts at its default blank start event.
     * @type {Array<RestartProcessInstanceModificationInstructionDto>}
     * @memberof RestartProcessInstanceDto
     */
    instructions?: Array<RestartProcessInstanceModificationInstructionDto> | null;
}
