/* tslint:disable */
/* eslint-disable */
/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { JobQueryDto } from './job-query-dto';
/**
 * Defines the number of retries for a selection of jobs. Please note that if both jobIds and jobQuery are provided, then retries will be set on the union of these sets.
 * @export
 * @interface SetJobRetriesDto
 */
export interface SetJobRetriesDto {
    /**
     * A list of job ids to set retries for.
     * @type {Array<string>}
     * @memberof SetJobRetriesDto
     */
    jobIds?: Array<string> | null;
    /**
     * 
     * @type {JobQueryDto}
     * @memberof SetJobRetriesDto
     */
    jobQuery?: JobQueryDto;
    /**
     * An integer representing the number of retries. Please note that the value cannot be negative or null.
     * @type {number}
     * @memberof SetJobRetriesDto
     */
    retries?: number | null;
}
