/* tslint:disable */
/* eslint-disable */
/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TelemetryProductDto } from './telemetry-product-dto';
/**
 * 
 * @export
 * @interface TelemetryDataDto
 */
export interface TelemetryDataDto {
    /**
     * An id which is unique for each installation of Camunda. It is stored once per database so all engines connected to the same database will have the same installation ID. The ID is used to identify a single installation of Camunda Platform.
     * @type {string}
     * @memberof TelemetryDataDto
     */
    installation?: string | null;
    /**
     * Information about the product collection telemetry data.
     * @type {{ [key: string]: TelemetryProductDto; }}
     * @memberof TelemetryDataDto
     */
    product?: { [key: string]: TelemetryProductDto; } | null;
}
