/* tslint:disable */
/* eslint-disable */
/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.18.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TelemetryCountDto
 */
export interface TelemetryCountDto {
    /**
     * An integer value representing the count for this metric.
     * @type {number}
     * @memberof TelemetryCountDto
     */
    count?: number | null;
}
